### ISSUE TITLE
Review request

### ISSUE THREAD

**Issue by Juanpa8830** [Juanpa8830/catalog_of_my_things#35]
# Hi reviewer:

## We are two people in our team.

- The team member assigned for "Team member 1" is @Juanpa8830 
- The team member assigned for "Team member 2" is @Oscar-Espinoza

**Comment by Gambit142** [comment]
Hi @Juanpa8830 @Oscar-Espinoza 👋, 

Good job so far!

## Highlights
- Used recommended kanban template ✔️ 
- All cards are assigned ✔️ 
- Points for cards are shared evenly ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

Kindly make the following changes to the Kanban board:

1. Kindly add a description to each card on the kanban board. To add the description, you would need to click on the blue underlined link. The clicking event will pop up a card to the right side and you would be able to add the description to each card. Kindly check the screenshot below to see what the card looks like. 👍 💻
 
![Screenshot_4](https://user-images.githubusercontent.com/77106962/228049920-a3b51c33-5064-4bf9-beb2-70d6cc165a47.png)

2. Based on the guideline, `Student 1` needs to implement all features for the `Book` and `Label` classes and not while `Student 2` needs to implement all features concerning `MusicAlbum` and `Genre` classes. You can read this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) to confirm. 👍 😎 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Juanpa8830** [comment]
hi @Gambit142, thanks for your review.

I think the tasks you are checking are the ones assigned to team member 3. In this case, according to the requirements we distributed this tasks for team member 1 and team member 2 as long as we are only two people in the team. On the other hand, we did not ad description to all the tasks because in the "divided requirements" lesson, there are some tasks that do not have any more information to add. However, if you check the "implement methods" task, it containd a description of each method for each team member.

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯  
- Descriptive info ✔️
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
